---
name: Setup uv and Handle Its Cache
description: Downloads and installs the Python uv packaging manager and handles its cache.
author: Hynek Schlawack
branding:
  icon: package
  color: purple

inputs:
  cache-suffix:
    description: A suffix to append to the cache key.
    required: false
    default: ""

  cache-dependency-path:
    description: Hash this file and use it as part of the cache key.
    required: false
    default: ""

runs:
  using: composite

  steps:
  - name: Install uv on Linux or macOS
    run: curl -LsSf https://astral.sh/uv/install.sh | bash
    shell: bash
    if: runner.os != 'Windows'

  - name: Install uv on Windows
    run: irm https://astral.sh/uv/install.ps1 | iex
    shell: pwsh
    if: runner.os == 'Windows'

  - name: Find uv cache
    run: echo "UV_CACHE=$(uv cache dir)" >>$GITHUB_ENV
    shell: bash

  - name: Compute cache suffix by hashing ${{ inputs.cache-dependency-path }}
    run: |
      echo "HASH_CACHE_SUFFIX=-${{ hashFiles(inputs.cache-dependency-path) }}" >>$GITHUB_ENV
    shell: bash
    if: inputs.cache-dependency-path != ''

  - name: Load uv cache
    uses: actions/cache@v4
    with:
      path: ${{ env.UV_CACHE }}
      key: uv-${{ runner.os }}${{ inputs.cache-suffix }}${{ env.HASH_CACHE_SUFFIX }}
