---
name: CI

on:
  push:
      branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1" # Make tools pretty.

permissions: {}

jobs:
  check-install-no-date-suffix:
    name: Install w/o specifying a date suffix
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: action
          persist-credentials: false

      - uses: ./action
        with:
          cache-date-suffix: ""

      - run: |
          uv venv
          uv pip install attrs


  check-hash-deps-path:
    name: Hash a file
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: action
          persist-credentials: false

      - uses: ./action
        with:
          cache-suffix: -LE-SUFFIX
          cache-dependency-path: "**/LICENSE"

      - run: |
          uv venv
          uv pip install attrs
